name: Run plugin workflow

on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    call-test-workflow:
        name: Call workflow for tests
        strategy:
            matrix:
                include:
                    - shopware-version: '5.6'
                      php-version: '7.2'
                      mysql-version: '5.7'
                    - shopware-version: '5.7'
                      php-version: '7.4'
                      mysql-version: '8.0'
                    - shopware-version: '5.7'
                      php-version: '8.2'
                      mysql-version: '8.0'

        uses: rathmerdominik/docker-images-testing/.github/workflows/php-code-analysis.yml@sw-27107/fix-workflows-for-shopware-and-plugins
        with:
            plugin-name: SwagUserPrice
            php-version: ${{ matrix.php-version }}
            shopware-version: ${{ matrix.shopware-version }}
            mysql-version: ${{ matrix.mysql-version }}

    call-analyse-workflow:
        name: Analyse code for SwagUserPrice
        uses: shopware5/docker-images-testing/.github/workflows/php-code-analysis.yml@main
        with:
            plugin-name: SwagUserPrice

    javascript-code-analysis:
        name: Javascript Code analysis
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/shopware5/docker-images-testing/install:shopware_5.7_8.0_7.4_none
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github_token }}

        env:
            GH_TOKEN: ${{ github.token }}

        steps:
            -   name: Move supervisord config
                run: /usr/bin/supervisord -c /etc/supervisord.conf &

            -   name: Checkout SwagUserPrice
                uses: actions/checkout@v3
                with:
                    path: plugin

            -   name: Move plugin
                run: mv "$(pwd)/plugin" /shopware/custom/plugins/SwagUserPrice

            -   name: Execute javascript code analysis
                run: |
                    cd /shopware/custom/plugins/SwagUserPrice
                    make check-js-code
