name: Run plugin workflow

on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    call-test-workflow:
        strategy:
            matrix:
                include:
                    - shopware-version: 'v5.6'
                      php-version: '7.2'
                      mysql-version: '5.7'
                    - shopware-version: '5.7'
                      php-version: '7.4'
                      mysql-version: '8.0'
                    - shopware-version: '5.7'
                      php-version: '8.2'
                      mysql-version: '8.0'

        uses: shopware5/docker-images-testing/.github/workflows/php-unit-tests-shopware.yml@main
        with:
            plugin-name: SwagUserPrice
            php-version: ${{ matrix.php-version }}
            shopware-version: ${{ matrix.shopware-version }}
            mysql-version: ${{ matrix.mysql-version }}

    call-analyse-workflow:
        name: Analyse code for SwagUserPrice
        uses: shopware5/docker-images-testing/.github/workflows/php-code-analysis.yml@main
        with:
            plugin-name: SwagUserPrice
